cc_test(
  name = "test_threadpool",
  size = "small",
  srcs = ["test_threadpool.cc"],
  deps = [
    "//dreadpools:dreadpools",
    "@com_google_googletest//:gtest_main"
  ],
)

cc_test(
  name = "test_queue",
  size = "small",
  srcs = ["test_queue.cc"],
  deps = [
    "//dreadpools:dreadpools",
    "@com_google_googletest//:gtest_main"
  ],
)
